package com.springbach.demo.mapper;

import com.springbach.demo.domain.Book;
import com.springbach.demo.domain.BookExample;

import java.util.List;

/**
 * Title:com.springbach.demo.mapper
 * Description:
 * Copyright: Copyright (c) 2018
 * Company: 北京思特奇信息技术股份有限公司
 *
 * @author dangqp
 * @version 1.0
 * @created 2018/09/13  18:36
 */

public class BookMapperImpl implements BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param example
     * @mbggenerated
     */
    public int countByExample(BookExample example) {
        return 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param example
     * @mbggenerated
     */
    public int deleteByExample(BookExample example) {
        return 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param example
     * @mbggenerated
     */
    public List<Book> selectByExample(BookExample example) {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param bookId
     * @mbggenerated
     */
    public Book selectByPrimaryKey(Long bookId) {
        return null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param record
     * @param example
     * @mbggenerated
     */
    public int updateByExampleSelective(Book record, BookExample example) {
        return 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_mysql
     *
     * @param record
     * @mbggenerated
     */
    public int updateByExample(Book record) {
        return 0;
    }

    public int updateById(Book bookId) {
        return 0;
    }

    public Book selectBookById(Long bookId) {
        return null;
    }

    /**
     * 查询所有记录
     */
    public List<Book> selectBook() {
        return null;
    }
}
