/**
 * @author yangxya create by 
 */
package com.example.demo.mapper;

import com.example.demo.domain.Book201809;
import java.util.List;

public interface Book201809Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int deleteByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int insert(Book201809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int insertSelective(Book201809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    Book201809 selectByPrimaryKey(Long bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    List selectByDto(Book201809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int deleteByDto(Book201809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int updateByPrimaryKeySelective(Book201809 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_201809
     *
     * @MybatisMapper
     */
    int updateByPrimaryKey(Book201809 record);
}