/**
 * @author yangxya create by 
 */
package com.example.demo.domain;

public class Book201809 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_201809.book_id
     *
     * @MybatisMapper
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_201809.name
     *
     * @MybatisMapper
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_201809.number
     *
     * @MybatisMapper
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_201809.book_id
     *
     * @return the value of book_201809.book_id
     *
     * @MybatisMapper
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_201809.book_id
     *
     * @param bookId the value for book_201809.book_id
     *
     * @MybatisMapper
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_201809.name
     *
     * @return the value of book_201809.name
     *
     * @MybatisMapper
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_201809.name
     *
     * @param name the value for book_201809.name
     *
     * @MybatisMapper
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_201809.number
     *
     * @return the value of book_201809.number
     *
     * @MybatisMapper
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_201809.number
     *
     * @param number the value for book_201809.number
     *
     * @MybatisMapper
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * 新增：处理表名
     */
    private String tableName;

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
}